# File: azure-pipelines.yml
# Date: 4-Jul-2019 jdw Created pipeline
#       8-Jul-2019 jdw add macos test/publish
#       8-Jul-2019 jdw templatize
#       9-Jul-2019 jdw add publish jobs
#      16-Oct-2024 dwp update to python 3.10
#
#       Only running py310 tasks with mysql and mongodb ----
#
name: $(BuildDefinitionName)_$(Date:yyyyMMdd)$(Rev:.rr)

name: $(BuildDefinitionName)_$(Date:yyyyMMdd)$(Rev:.rr)

trigger:
  - master

pr:
  - master

schedules:
  - cron: "0 12 * * 0"
    displayName: Weekly Sunday build
    branches:
      include:
        - master
    always: true

jobs:
  - template: azure-template-tox-job.yml
    parameters: { tox: "format_pep8", python: "3.13", os: "linux", fixtures: 'mongodb'}
  - template: azure-template-tox-job.yml
    parameters: { tox: "lint_pylint", python: "3.13", os: "linux", fixtures: 'mongodb'}
  # - template: azure-template-tox-job.yml
  #   parameters: { tox: "test_coverage", python: "3.13", os: "linux", fixtures: 'mongodb'}
    #
  - template: azure-template-tox-job.yml
    parameters: { tox: "py313", python: "3.13", os: "linux", fixtures: 'mongodb'}  #
  # - template: azure-template-tox-job.yml
  #   parameters: { tox: "py313", python: "3.13", os: "macos", fixtures: 'mongodb'}
  #
  - template: azure-template-publish-job.yml
    parameters: { tox: "py313", python: "3.13", os: "linux" }
  #
